### ISSUE TITLE
Author instructions / Compiling the book using Docker / 2021-11-19

### ISSUE THREAD

**Issue by AndreaCensi** [ACT4E/ACT4E#223]
Chapter: Author instructions
Section: Compiling the book using Docker
Version: 2021-11-19

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

**Comment by gzardini** [comment]
This was a test. Solved.
