### ISSUE TITLE
Sets and functions / New sets from old / 2021-12-02

### ISSUE THREAD

**Issue by nagyzoltan** [ACT4E/ACT4E#226]
Chapter: Sets and functions
Section: New sets from old
Version: 2021-12-02

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

The example for A u B seems incorrect. It seems it should include the banana and the juicebox as well.

<img width="369" alt="Screen Shot 2021-12-06 at 12 19 35" src="https://user-images.githubusercontent.com/15887774/144900424-6fd2fd97-b31a-4220-acdb-81e55fd81735.png">

**Comment by gzardini** [comment]
This has been corrected and will appear in the next book update. 

Thank you for the help in correcting the book.

Best,

Gioele
