### ISSUE TITLE
Programming Exercise for Sets and Functions

### ISSUE THREAD

**Issue by SylvainFricker** [ACT4E/ACT4E#323]
Chapter: Sets and functions
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Representing sets
Version: 2022-02-28

Check all that apply:
- ( ) Something incorrect
- (x) Something not clear
- (x) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

1) Add coment about either implementing MyFiniteSet in a new file (for instance my_finite_set) and importing the class in the solution template (sets_representation.py) as from .my_finite_set import MyFiniteSet, or implement in the same file (i.e. sets_representation.py)

2) On page 63, you refer to a line in listing 14, all_elements = sorted(f.elements()), however, there is no such line in listing 14 (instead it is all_elements = [f.save(h, _) for _ in f.elements()]

**Comment by AndreaCensi** [comment]
Hi Sylvain, feel free to make these changes directly.
