### ISSUE TITLE
Sets and functions - Wrong command for testing the solution -  Representing sets / 2022-03-01

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#336]
Chapter: Sets and functions P.62
Section: Code exercise B.1 (TestFiniteSetRepresentation) - Representing sets
Version: 2022-03-01

Check all that apply:
- ( x ) Something incorrect
- (  ) Something not clear
- (  ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
**Problem:**   stated in the instruction that we should check the solution by `act4e-check TestTestFiniteSetRepresentation`
**Correction:** should be `act4e-check TestFiniteSetRepresentation` instead

**Comment by AndreaCensi** [comment]
thanks for the report

@gzardini I pushed a fix to branch alphubel-stage-AC-feb26. Check that his solves the issue and publish a new version.

**Comment by gzardini** [comment]
@AndreaCensi it fixes the issue, and I see you did already merge the branch, right?
