### ISSUE TITLE
Sets and functions /  Type parameters not consistently used -  Representing sets / 2022-03-01

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#338]
Chapter: Sets and functions
Section: Book page p. 61 Representing sets
Version: 2022-03-01

Check all that apply:
- ( ? ) Something incorrect
- ( x ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

**Description used parameters E & R**
_"The two type parameters E and R correspond to
the Python type that they serialize and to the resulting serialization format."_

**Actual parameters used in the classes Loader, Saver and Serializer**
![image](https://user-images.githubusercontent.com/82619264/156822518-3f676b22-54ef-4109-8815-ec8fc4703122.png)

**Comment by AndreaCensi** [comment]
Thanks, will be fixed in the next release.
