### ISSUE TITLE
Sets and functions - Set products: Confusing description / 2022-03-08

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#355]
Chapter: Sets and functions
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Set products
Version: 2022-03-08

Check all that apply:
- ( ) Something incorrect
- ( x ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

![image](https://user-images.githubusercontent.com/82619264/157510349-5891c0ce-efe5-4570-a82b-a35807ee4e3e.png)

At book page p.66. It stated that:  """A set product is a setoid that can be factorized."""

I think nowhere in the script states what the "factorisation" of the setoid means, is it possible to make the definition of it more explicit?

**Comment by AndreaCensi** [comment]
good point

**Comment by AndreaCensi** [comment]
fixed in the next version
