### ISSUE TITLE
Sets and functions / Functions / 2022-03-08

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#357]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-08

Check all that apply:
- ( x ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
p.77
![image](https://user-images.githubusercontent.com/82619264/157662752-da86c019-6063-41bc-8a74-28e7edf2c8a9.png)

The 4th line in the 2nd paragraph:
The composition of the functions f and g should have the set "1" as domain and the set B as its codomain instead of A.

**Comment by AndreaCensi** [comment]
correct, thanks
