### ISSUE TITLE
Sets and functions / \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Representing sets/ 2022-03-09

### ISSUE THREAD

**Issue by HuangYujun-JunkyTalent** [ACT4E/ACT4E#359]
Chapter: Sets and functions
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Representing sets
Version: 2022-03-09

Check all that apply:
- (✅) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

It seems that the example of using class method to access the elements of a set, rather than directly access the protected class member, is not updated. And the example is not compatible with the actual code in this version. The code now uses `all_elements = [f.save(h, _) for _ in f.elements()]`, but the example still says `all_elements = sorted(f.elements())` and `all_elements = sorted(f._elements)`.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/91888165/157729087-44dad47e-8316-46a6-9cd1-6fc48b0dd5c7.png">

**Comment by AndreaCensi** [comment]
thanks, it's fixed in the next version

@gzardini need to update the book available on moodle
