### ISSUE TITLE
\wHomos  / Generators and relations / 2022-03-12

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#369]
Chapter: \wHomos 
Section: Generators and relations
Version: 2022-03-12

Check all that apply:
- ( ) Something incorrect
- ( x ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

![image](https://user-images.githubusercontent.com/82619264/158195651-33be947b-c803-44c3-8a74-6010a2011ad6.png)

The definition and the example together is a bit confusing. I am confused whether we could also have 4 distinct elements or only 2 distinct elements chosen for the equation (which is the case of the example beneath).

**Comment by JonathanLorand** [comment]
Thanks a lot for submitting your comments!
I've added some new material in this section now that should help clarify (it should appear in the book tonight). If it still seems confusing, please let us know.
