### ISSUE TITLE
Putting things together / Commutativity and associativity / 2022-03-14: typo "Annihalitive element?"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#371]
Chapter: Putting things together
Section: Commutativity and associativity
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

Table 2.1.: Properties of color composition rules has a typo: "Annihalitive element?" --> "Annihilative element?"

**Comment by AndreaCensi** [comment]
Thanks, will be fixed in the next release.
