### ISSUE TITLE
Sets and functions / Sets / 2022-03-14: typo "difference ways of indicating one ..."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#374]
Chapter: Sets and functions
Section: Sets
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

Typo in Section 4.2. Sets / Specifying a set by naming its elements:
"...difference ways of indicating one and the same set." --> "...different ways of indicating one and the same set."

**Comment by AndreaCensi** [comment]
thanks, fixed in the next version
