### ISSUE TITLE
Sets and functions / New sets from old / 2022-03-14: typo "Another was to represent the Cartesian product..."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#376]
Chapter: Sets and functions
Section: New sets from old
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

Typo in section 4.3. New sets from old / Cartesian product:
"Another was to represent the Cartesian product is the following:" --> "Another way to represent the Cartesian product is the following:"

**Comment by AndreaCensi** [comment]
thanks, fixed in the next version
