### ISSUE TITLE
Sets and functions / New sets from old / 2022-03-15

### ISSUE THREAD

**Issue by eliaspratschke** [ACT4E/ACT4E#379]
Chapter: Sets and functions
Section: New sets from old
Version: 2022-03-15

Check all that apply:
- ( ) Something incorrect
- ( x) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

Equation 41 uses the symbol for intersection before it is defined in the context of sets. It seems like 41 and the sentence before it would make more sense as a second example of set intersection after equation 43.

**Comment by AndreaCensi** [comment]
Thanks, it will be fixed in the next version.
