### ISSUE TITLE
Sets and functions / Type Theory / 2022-03-15

### ISSUE THREAD

**Issue by justshim** [ACT4E/ACT4E#380]
Chapter: Sets and functions
Section: Type Theory
Version: 2022-03-15

Check all that apply:

( x) Something incorrect
( ) Something not clear
( ) Something missing
Please describe more in detail below. Feel free to change the title to something more informative.

The equal function in equation 62 is incorrect. It should be

equal = [(a,b), (c,d)] -> equal_int(ad,bc)

**Comment by AndreaCensi** [comment]
Thanks, will be corrected in the next version.
