### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: typo "...can be show to be a continuous function, ..."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#384]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

There is a typo in section 4.11 Functions / Specifying functions:
"...can be show to be a continuous function" --> "...can be shown to be a continuous function"

**Comment by AndreaCensi** [comment]
thanks, will be fixed in the next version
