### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: typo "it might then perform as series of computations"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#415]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 4.11. Functions / Functions as deterministic machines:
"it might then perform as series of computations" --> "it might then perform a series of computations"

**Comment by AndreaCensi** [comment]
thanks!
