### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: incorrect / unclear "(for any set~\setB)"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#416]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section "4.11. Functions / To and from the empty set", the following is incorrect / unclear to me:
In the last paragraph "On the other hand..."
We have "A to Emptyset", therefore "B = Emptyset". I think the statement in parentheses "(for any set B)" is incorrect and needs to be omitted.

**Comment by AndreaCensi** [comment]
@JonathanLorand address this?

**Comment by JonathanLorand** [comment]
fixed. 
thank you!
