### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: typo "...as a way to relation one set to another."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#417]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo In section 4.11. Functions / Sets of functions:
"...as a way to relation one set to
another." --> "as a way to relate one set to
another."

**Comment by AndreaCensi** [comment]
thanks, fixed
