### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: typo: "...as we did above, by saying the at..."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#419]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 4.11. Functions / The compositional perspective:
"...as we did above, by saying the at..." -- > "as we did above, by saying that..."

**Comment by AndreaCensi** [comment]
thanks!
