### ISSUE TITLE
Relations / Distribution networks / 2022-03-14: incorrect: "transistor" --> "transformer"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#423]
Chapter: Relations
Section: Distribution networks
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 5.1 Distribution networks, the word "transistor" should be replaced with "transformer".

**Comment by AndreaCensi** [comment]
thanks!
