### ISSUE TITLE
Putting things together / Commutativity and associativity / 2022-03-14: incorrect / unclear commutativity definition

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#428]
Chapter: Putting things together
Section: Commutativity and associativity
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
At the start of section 2.4. Commutativity and associativity, the sentence "For example, we can define as commutativity as follows." has one "as" too much.
Furthermore, the next sentence "A composition is commutative if getting a C from an A and B holds if and only if A and B give a C:" may be incorrect. I think one should switch the second "A and B" to "B and A" to correct it.

**Comment by AndreaCensi** [comment]
right

**Comment by AndreaCensi** [comment]
fixed
