### ISSUE TITLE
The view from above / Compositional thinking for engineers / 2022-03-14: typo: themselves --> himself

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#429]
Chapter: The view from above
Section: Compositional thinking for engineers
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 1.1 Sapiens: a compositional retrospective:
"Once, a single sapiens had the ability to survive by themselves" -->
"Once, a single sapiens had the ability to survive by himself"

**Comment by AndreaCensi** [comment]
Ah, this is an Americanism → we don't know if the sapiens is male or female, then we say "themselves".
