### ISSUE TITLE
Sets and functions / New sets from old / 2022-03-14: inappropriate usage of word "clear"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#430]
Chapter: Sets and functions
Section: New sets from old
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 4.3. New sets from old, the word "clear" is being used inappropriately in my opinion, because the superscript "c" refers to "complement" and could wrongly be understood to refer to "clear":
"When the set A is clear, the notation Sc is sometimes used instead of A\S."
--> e.g. "When the set A is given through its context, the notation Sc is sometimes used instead of A\S."

**Comment by JonathanLorand** [comment]
fixed. 
thanks!
