### ISSUE TITLE
Sets and functions / New sets from old / 2022-03-14: Unclear / too long sentence

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#431]
Chapter: Sets and functions
Section: New sets from old
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 4.3. New sets from old / Tuples, there is one sentence which is too long / unclear in my opinion.
"Typically, we will use tuples in situations where we also specify, for each entry of the tuple, a set of which that entry is an element or a type of thing of which that entry is an instance."
--> e.g. "Typically, we will use tuples in situations where we also specify, for each entry of the tuple, a set. Each entry is an element of this set or (more generally) an instance of a type of thing of this set."

**Comment by JonathanLorand** [comment]
edited. 
thanks!
