### ISSUE TITLE
Sets and functions / New sets from old / 2022-03-14: typo: A and A

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#432]
Chapter: Sets and functions
Section: New sets from old
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 4.3. New sets from old / Cartesian product / Remark 4.2.:
"For finite sets A and A" --> "For finite sets A and B"

**Comment by AndreaCensi** [comment]
thanks, fixed
