### ISSUE TITLE
Sets and functions / Code exercises - Type theory / 2022-03-14: Unclear statement Composition over inheritance"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#435]
Chapter: Sets and functions
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Type theory
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a statement in section "4.4. Type Theory / Python and other design choices / > Composition over inheritance:" which confuses me:
"An example use of inheritance would be saying: “a poset is a set which also has an order relation”; composition would be saying “a poset is a tuple of a set and an order relation”." 
First of all, I don't know if we are talking here about "mathematical composition" or "object-oriented (OO) composition" (where OO composition is distinct to association and aggregation) or if the two are one and the same "composition".
Secondly, I personally have an ambiguous association with the statement "a poset is a ...". It could either mean "a poset is an implementation of ..." (which suggests inheritance) or "a poset is an instance of ..." (which suggests the concrete type). To me it is not directly clear what the two exemplary statements "a poset is a..." mean. A UML diagram or an extended verbal statement could clarify this in my opinion.

**Comment by AndreaCensi** [comment]
fixed
