### ISSUE TITLE
Relations / Relations and functions / 2022-03-14: typo "how is relation composition relate"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#436]
Chapter: Relations
Section: Relations and functions
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 5.6. Relations and functions / Composing functions:
"... how is relation composition relate to the ‘usual’ way of composing of functions?" -->
"... how is relation composition related to the ‘usual’ way of composing functions?" OR
"... how does relation composition relate to the ‘usual’ way of composing functions?"

**Comment by AndreaCensi** [comment]
thanks, fixed
