### ISSUE TITLE
Relations / Transitivity / 2022-03-14: typo "that are already been seen."

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#437]
Chapter: Relations
Section: Transitivity
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 5.14. Transitivity:
"But do not mark for expansion those that are already been seen." -->
"But do not mark for expansion those that have already been seen."

**Comment by AndreaCensi** [comment]
thanks ,fixed
