### ISSUE TITLE
 Relations / Transpose of a relation / 2022-03-14: typo "If"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#438]
Chapter: Relations
Section: Transpose of a relation
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
There is a typo in section 5.9. Transpose of a relation / Remark 5.11.:
"2. If R is everywhere-defined..." --> "2. R is everywhere-defined..."
"3. If R is single-valued..." --> "3. R is single-valued..."

**Comment by AndreaCensi** [comment]
thanks, fixed
