### ISSUE TITLE
Relations / Equivalence relations / 2022-03-14: unclear / incorrect Definition 5.27

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#439]
Chapter: Relations
Section: Equivalence relations
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
The Definition 5.27 (Equivalence relation) in section 5.15. Equivalence relations is not strictly correct in my opinion:
"An endorelation R: A   A is an equivalence relation if it is symmetric, reflexive, and transitive. We write x   y if xRy."
The last part "We write x   y if xRy." I think is only true if it is also symmetric, reflexive, and transitive (i.e. For example one could clarify the Definition as follows:
--> "An endorelation R: A   A is an equivalence relation if it is symmetric, reflexive, and transitive. We write x   y if the relation xRy is an equivalence relation." (And therefore implies that the symmetric, reflexive, and transitive properties also need to hold in order to use the newly introduced notation.)

In the first sentence we introduce R as endorelation. If the symmetric, reflexive, and transitive properties don't hold, R is still an endorelation but not an equivalence relation. Therefore the following sentence would be incorrect in my opinion, because the newly introduced symbol ~ should only be used for endorelations which are also equivalence relations (I think).

**Comment by JonathanLorand** [comment]
fixed. 
thank you!
