### ISSUE TITLE
Unus Pro Omnibus, Omnes Pro Uno / Magmas / 2022-03-14: unclear / missing Definition

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#440]
Chapter: Unus Pro Omnibus, Omnes Pro Uno
Section: Magmas
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- (X) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
The terminology of Definition 6.1 in section 6.1 Magmas is not completely clear to me.
"A magma S is a set S, together with a binary operation ; : S   S   S."
Can we always call the binary operation of a Magma "composition"? I think so, but it is not explicitly stated in the Definition.

If it is a composition operation, then I think this could be added to the Definition (---> e.g. "A magma S is a set S, together with a composition operation ; : S   S   S."
If it is not strictly a composition operation, then why would we use the "then" symbol which we already use for composition? In that case I also think it might make sense to call it a "binary relation" instead of a "binary operation".
(I hope this makes sense)

**Comment by AndreaCensi** [comment]
Thanks, clarified. Yes, we always call it "composition"
