### ISSUE TITLE
Putting things together / Isomorphisms / 2022-03-14: unclear “spot how different things are the same at some level of abstraction”

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#454]
Chapter: Putting things together
Section: Isomorphisms
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 2.6. Isomorphisms the statement “spot how different things are the same at some level of abstraction” is rather confusing because when first reading it, my mind reads the first part of the statement "spot how different things are." as if it could be a sentence on its own. Meaning, "things are different" and not "different things". But the key message should be the opposite.
A workaround could be to say “spot how several (different) things are the same at some level of abstraction”.

**Comment by AndreaCensi** [comment]
thanks, fixed
