### ISSUE TITLE
Sets and functions / Logical preliminaries / 2022-03-14: incorrect "exists" --> "there exists"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#455]
Chapter: Sets and functions
Section: Logical preliminaries
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 4.1. Logical preliminaries / Variables and quantifiers:
In the first sentence I think the statement
"...read “exists” and “for all”, respectively." should be corrected to
"...read “there exists” and “for all”, respectively."

**Comment by AndreaCensi** [comment]
thanks, fixed
