### ISSUE TITLE
Sets and functions / Sets / 2022-03-14: unclear: graphical depiction of parentheses in subsequent equivalence statements

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#456]
Chapter: Sets and functions
Section: Sets
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 4.2. Sets / Equality, the depiction of "A = B <=> x \in A <=> x \in B" with the double bar is unclear to me. I think there would need to be parentheses around the statement (x \in A <=> x \in B) for it to be logically correct. I also think that the wider double bar induces these parentheses, but this has never been mentioned and I think it needs to be explicitly addressed.

**Comment by AndreaCensi** [comment]
added explanation
