### ISSUE TITLE
Sets and functions / Functions / 2022-03-14: unclear Definition 4.15 (Sum of functions)

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#457]
Chapter: Sets and functions
Section: Functions
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 4.11. Functions / Product and sum of functions / Definition 4.15 (Sum of functions):
There is a function called "f", but also an input argument called "f" in <2,f>. It might make sense to call the two input arguments <1,a> and <2,c> because a is an element of A and c is an element of C.

**Comment by AndreaCensi** [comment]
yep! fixed.
