### ISSUE TITLE
Relations / Endorelations / 2022-03-14: missing "antireflexive", "intransitive", "antitransitive"

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#458]
Chapter: Relations
Section: Endorelations
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- (X) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 5.11. Endorelations, I think it could be beneficial to also state the properties "antireflexive", "intransitive", "antitransitive". By listing them in "Table 5.1.: Summary of endorelation properties" in the following way:

REFLEXIVITY   SYMMETRY         TRANSITIVITY     TOTALITY
reflexive           symmetric            transitive              total
irreflexive         asymmetric          intransitive           ???
antireflexive     antisymmetric      antitransitive       ???

Also, currently "Table 5.1.: Summary of endorelation properties: Irreflexive" has a "False : 1" where it should only be "False".

I also don't know why "Transitivity" deserves its own chapter, maybe "Reflexivity" and "Symmetry" also deserve one...

**Comment by AndreaCensi** [comment]
We chose the set of "essential" properties. We are not going to use the rest.

Transitive gets a section by itself because the definition is similar to the composition of morphisms. (a set with a transitive relation is a category). Also we need "transitive closure".
