### ISSUE TITLE
Unus Pro Omnibus, Omnes Pro Uno / Semigroups / 2022-03-14: unclear: "multiplication" --> "composition"?

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#459]
Chapter: Unus Pro Omnibus, Omnes Pro Uno
Section: Semigroups
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 6.2. Semigroups / Remark 6.5., in the second paragraph, the term "multiplication" I think should be replaced with "composition" to be stringent (in case "multiplication" is a synonym for "composition", I think it should be stated somewhere, which I think it isn't):
"...this is practical when it is clear from context which multiplication operation we are considering, or when it is not necessary to refer to the multiplication explicitly." -->
"...this is practical when it is clear from context which composition operation we are considering, or when it is not necessary to refer to the composition explicitly."

**Comment by AndreaCensi** [comment]
You're right. We should call them "composition".
We wrote "multiplication" because the traditional symbol to use is · rather than ;.
