### ISSUE TITLE
Unus Pro Omnibus, Omnes Pro Uno / Semigroups / 2022-03-14: unclear Definition 6.13 (Subsemigroups)

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#460]
Chapter: Unus Pro Omnibus, Omnes Pro Uno
Section: Semigroups
Version: 2022-03-14

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 6.2. Semigroups / Subsemigroups / Definition 6.13, the semigroup S = <S, ; , id> has an identity element defined, but in the definition of semigroup we did not require an identity element.
I think either the identity function should be added to the definition of semigroup or the definition of subsemigroup could be stated as S = <S, ;>.

**Comment by AndreaCensi** [comment]
thanks, fixed - (no identity for semigroups!)
