### ISSUE TITLE
Life is hard / Antitone maps / 2022-03-29

### ISSUE THREAD

**Issue by SylvainFricker** [ACT4E/ACT4E#464]
Chapter: Life is hard
Section: Antitone maps
Version: 2022-03-29

Check all that apply:
- ( ) Something incorrect
- (x) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In the programming exercise on montone maps, it is not really clear what the class FiniteMonotoneMap is used for. Should it be implemented? Will it be used later? There are no tests for the implementation of this class..

**Comment by AndreaCensi** [comment]
good point, commented out for now
