### ISSUE TITLE
Graphs / Graph homomorphisms / 2022-03-23

### ISSUE THREAD

**Issue by LouisaHil** [ACT4E/ACT4E#471]
Chapter: Graphs
Section: Graph homomorphisms
Version: 2022-03-23

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
solution exercise 20 on page 287 : I am not certain the solution is correct . Tor F-->(5) , why is is F->(5)=IV and not III . I understood  that F.(e)=v and F.(a)= alpha and then from src(5)->tgt(5) we would have F->(5)=III. Where am I wrong ?

**Comment by gzardini** [comment]
@LouisaHil Thank you, typo fixed and will be solved in the next public version.
