### ISSUE TITLE
(Semi)categories / Diagrams / 2022-03-15

### ISSUE THREAD

**Issue by eliaspratschke** [ACT4E/ACT4E#477]
Chapter: (Semi)categories
Section: Diagrams
Version: 2022-03-15

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

In the second paragraph, the figure labelling is off. Fig.2 is referenced when talking about morphisms f, g and h, but in Fig.2 there is only f and g. I assume you mean Fig. 4 which would make sense in the context.

**Comment by AndreaCensi** [comment]
@JonathanLorand this seems fixed in the current version. please verify.

**Comment by eliaspratschke** [comment]
It is.
