### ISSUE TITLE
(Semi)categories / Diagrams / 2022-04-03 - Sentence ending

### ISSUE THREAD

**Issue by rubimat** [ACT4E/ACT4E#480]
Chapter: (Semi)categories
Section: Diagrams
Version: 2022-04-03

Check all that apply:
- ( ) Something incorrect
- ( ) Something not clear
- (x) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

In the first sentence, it sounds like the description for the arrows is missing. So it might be something like: "... with nodes representing objects and directed arrows corresponding to morphisms." or similar.

**Comment by gzardini** [comment]
Solved, appearing in next public version.
