### ISSUE TITLE
(Semi)categories / \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Semicategories / 2022-04-06

### ISSUE THREAD

**Issue by SylvainFricker** [ACT4E/ACT4E#491]
Chapter: (Semi)categories
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Semicategories
Version: 2022-04-06

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

I think the tests are not in agreement with the definition of level in table 14.1. In the test it says that the morphism "f;f;f;f" is in level 3 while I believe it should be in level 2.

**Comment by AndreaCensi** [comment]
fixed
