### ISSUE TITLE
Processes and actions / Moore machines, first version / 2022-04-11

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#498]
Chapter: Processes and actions
Section: Moore machines, first version
Version: 2022-04-11

Check all that apply:
- ( ) Something incorrect
- (x ) Something not clear
- ( x? ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
![image](https://user-images.githubusercontent.com/82619264/163576107-ccd626bd-e814-40a5-b5fe-f7a8fc86163e.png)

Is the sequence corresponding to the index 1 missing? i.e. we should have for the definition of the function u as followed:

![image](https://user-images.githubusercontent.com/82619264/163576610-f0d3b0d3-f4ce-4cba-a1cb-24c6c238dfe0.png)

**Comment by gzardini** [comment]
Thanks for catching the typo.
It will be corrected in the next public version.
