### ISSUE TITLE
Processes and actions / Different actions of Moore machines / 2022-04-11

### ISSUE THREAD

**Issue by rubimat** [ACT4E/ACT4E#521]
Chapter: Processes and actions
Section: Different actions of Moore machines
Version: 2022-04-11

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

In section "Changing the signal spaces" in the second sentence there is a "the" too much.

**Comment by gzardini** [comment]
Solved, thanks.
