### ISSUE TITLE
Culture / Diagrams conventions don't matter / 2022-04-11

### ISSUE THREAD

**Issue by rubimat** [ACT4E/ACT4E#522]
Chapter: Culture
Section: Diagrams conventions don't matter
Version: 2022-04-11

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

In the first sentence of the section "...we are flexed..." may be replaced with "...we have flexed..."

**Comment by gzardini** [comment]
Thank you, solved.
