### ISSUE TITLE
Parallelism / Functorial stacking semicategories / 2022-04-11

### ISSUE THREAD

**Issue by rubimat** [ACT4E/ACT4E#524]
Chapter: Parallelism
Section: Functorial stacking semicategories
Version: 2022-04-11

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

In Example 31.10 in the sentence before eq. 28 it says ".. for any (a,b) el of A x B." but in eq. 28 (a,d) gets inserted. --> change to ".. for any (a,d) el of A x D." .

**Comment by gzardini** [comment]
Solved.
