### ISSUE TITLE
Parallelism / Parallel stacking / 2022-04-11

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#529]
Chapter: Parallelism
Section: Parallel stacking
Version: 2022-04-11

Check all that apply:
- ( x ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In the second paragraph on page 430 we have the following description for "composing parallely"
![image](https://user-images.githubusercontent.com/82619264/167361668-e721f1fd-4e74-4c47-b4e1-d924bbd10229.png)

Shouldn't the composition be **f_1 X f_2 : AXC --> BXD**?

**Comment by gzardini** [comment]
Yes, thank you, the correction will appear in the next public version.
