### ISSUE TITLE
Parallelism / Functorial stacking semicategories / 2022-04-11

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#532]
Chapter: Parallelism
Section: Functorial stacking semicategories
Version: 2022-04-11

Check all that apply:
- ( x ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

![image](https://user-images.githubusercontent.com/82619264/167665380-581a3c97-3113-4ae4-9d3c-2440196e7181.png)

In the proof for the morphism operation to be functiorial, shouldn't the element be <a,d> in AXD instead?

**Comment by gzardini** [comment]
Yes, it has already been fixed and will appear in the next public version. Thx.
