### ISSUE TITLE
Lattice structure / Interaction with series composition / 2022-05-11

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#535]
Chapter: Lattice structure
Section: Interaction with series composition
Version: 2022-05-11

Check all that apply:
- ( ) Something incorrect
- ( x ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

![image](https://user-images.githubusercontent.com/82619264/168281412-3a58b5c4-15c3-44ad-a60a-db06973aa7cd.png)

In the 5th line of the 1st paragraph it is mentioned that the DP category is compact closed but it seems like no definition of such "compact closed" can be found in the script. I am quite confused what it means here.

**Comment by AndreaCensi** [comment]
thanks, you are right, that part is not in the official book so far.

**Comment by AndreaCensi** [comment]
fixed in next version
