### ISSUE TITLE
Trade-offs / \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Measuring posets / 2022-06-04

### ISSUE THREAD

**Issue by youwuyou** [ACT4E/ACT4E#551]
Chapter: Trade-offs
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Measuring posets
Version: 2022-06-04

Check all that apply:
- ( x ) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

![image](https://user-images.githubusercontent.com/82619264/174987786-c876b5ef-e356-4d9f-9056-f370f3846136.png)

For the Mirsky's theorem, it shall be:
"A finite poset of height ℎ can be partitioned into **h** antichains."

**Comment by AndreaCensi** [comment]
thanks, fixed!
