### ISSUE TITLE
Exercises / \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Overview / 2022-06-04

### ISSUE THREAD

**Issue by gromige** [ACT4E/ACT4E#553]
Chapter: Exercises
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Overview
Version: 2022-06-04

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
"Option 2" is introduced "If you are not following a class where the instructors are using GitHub Classroom, this is the section for you. Otherwise, jump to Section 3.2." However, it is part of Section 3.2.

**Comment by AndreaCensi** [comment]
fixed
