### ISSUE TITLE
Trade-offs / \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Measuring posets / 2022-06-04

### ISSUE THREAD

**Issue by gromige** [ACT4E/ACT4E#563]
Chapter: Trade-offs
Section: \texorpdfstring {\usebox {\chaptergear }}{Code exercises -} Measuring posets
Version: 2022-06-04

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
"Theorem 9.21 (Mirsky’s theorem). A finite poset of height h can be partitioned into 𝑤 antichains." should be "Theorem 9.21 (Mirsky’s theorem). A finite poset of height h can be partitioned into **h** antichains."

**Comment by kimhanm** [comment]
has been fixed with #556 (commit dd77311)
