### ISSUE TITLE
Lattices / Lattices / 2022-06-04 Error in join and meet definition of USets and LSets

### ISSUE THREAD

**Issue by HuangYujun-JunkyTalent** [ACT4E/ACT4E#586]
Chapter: Lattices
Section: Lattices
Version: 2022-06-04

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

According to the definition of join (supremum) and meet (infimum), it seems that join in USets should be intersection of sets, meet in USets should be union of sets, not vice versa. A similar problem also occurs in the definition of LSets.

**Comment by antonioterpin** [comment]
Hi, thanks a lot for the comment. The way it is done is correct, but I can see the confusion. I tried to clarify the steps of the proof in https://github.com/ACT4E/ACT4E/pull/703
