### ISSUE TITLE
Monoidal categories / Monoidal categories / 2022-03-14: Mistake: Monoidal Categories / Remark 38.2?

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#602]
Chapter: Monoidal categories
Section: Monoidal categories
Version: 2022-03-14

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
Under section 38.1 Monoidal categories / Remark 37.2 on page 507, I think the phrase
"...and 𝐺 must act by 𝐺(𝑋) = 𝐹(𝑋)." should be
"and 𝐺 must act by 𝐺(𝑋) = 𝑋."

**Comment by antonioterpin** [comment]
Thank you, you are right and we addressed the issue with PR https://github.com/ACT4E/ACT4E/pull/669
