### ISSUE TITLE
Monotone Co-Design Theory /  Co-design problems / 2022-11-01: typo: Recursive constraints / Figure 25

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#615]
Chapter: Monotone Co-Design Theory
Section:  Co-design problems
Version: 2022-11-01

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 25.4. Co-design problems / Recursive constraints on page 366, there is a typo in Figure 25. The unit of the requirement motor torque for the chassis is denoted with [rad/s] instead of [Nm].

**Comment by antonioterpin** [comment]
Thank you! We addressed the issue in #677
