### ISSUE TITLE
Traced Monoidal categories /  Symmetric monoidal categories / 2022-11-01: Mistake in definition of monoidal product for DPs

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#616]
Chapter: Traced Monoidal categories
Section:  Symmetric monoidal categories
Version: 2022-11-01

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 37.3. Symmetric monoidal categories / DP is a symmetric monoidal category on page 519, the monoidal product on morphisms is defined to map
⟨⟨𝑎, 𝑐⟩∗, ⟨𝑏, 𝑑⟩⟩ ↦𝐝(𝑎∗, 𝑐) ∧ 𝐞(𝑐∗, 𝑑), which should be
⟨⟨𝑎, 𝑐⟩∗, ⟨𝑏, 𝑑⟩⟩ ↦𝐝(𝑎∗, b) ∧ 𝐞(𝑐∗, 𝑑),

**Comment by antonioterpin** [comment]
Thank you! We addressed the issue in https://github.com/ACT4E/ACT4E/pull/677
