### ISSUE TITLE
Adjunctions /  Galois connections / 2022-11-01

### ISSUE THREAD

**Issue by gromige** [ACT4E/ACT4E#623]
Chapter: Adjunctions
Section:  Galois connections
Version: 2022-11-01

Check all that apply:
- (x) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
(2) is wrong. Error is on the right side of ∧

**Comment by antonioterpin** [comment]
Thank you. You are right, the issue has already been resolved in a work-in-progress version of the book.
