### ISSUE TITLE
Trade-offs /  Ordered sets / 2022-12-09: Unclear condition for partial order on positive definite matrices

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#636]
Chapter: Trade-offs
Section:  Ordered sets
Version: 2022-12-09

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In Section 9.2. Ordered sets / Example: positive definite matrices as ellipsoids on page 157, it says:
"Note that the condition 𝐀 = 𝐁 is needed to ensure reflexivity.",
I don't understand this, could also be a mistake?

**Comment by kimhanm** [comment]
It seems like this sentence is not supposed to be there.
