### ISSUE TITLE
Monotone Co-Design Theory /  Co-design problems / 2022-12-09: Mistake example 25.19, equation (23)

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#641]
Chapter: Monotone Co-Design Theory
Section:  Co-design problems
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 25.4. Co-design problems / Example 25.19 / 3. Co-design constraints, the equation (23) should be:
"𝑟𝐞,𝐠 ⪯ 𝑓𝐝2", instead of
"𝑟𝐞,𝐠 ⪯ 𝑓𝐝1"

**Comment by antonioterpin** [comment]
Thank you! We addressed the issue in https://github.com/ACT4E/ACT4E/pull/676
