### ISSUE TITLE
Lattice structure /  Interaction with series composition / 2022-12-09: Typo 𝐝, (𝐝 ; 𝐞) ∈ HomDP(𝐏;𝐐)

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#643]
Chapter: Lattice structure
Section:  Interaction with series composition
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 28.2. Interaction with series composition / Lemma 28.3., it says:
"Given 𝐝, (𝐝 ; 𝐞) ∈ HomDP(𝐏;𝐐) and...", but I think it should be
"Given 𝐝, 𝐞 ∈ HomDP(𝐏;𝐐) and...".

**Comment by antonioterpin** [comment]
Thank you, you are right and we addressed the issue with PR https://github.com/ACT4E/ACT4E/pull/670
