### ISSUE TITLE
Parallelism /  Parallel stacking / 2022-12-09: Grammar mistake

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#645]
Chapter: Parallelism
Section:  Parallel stacking
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 31.2. Parallel stacking / Types of stacking operations / 3. Monoidal stacking semicategory on page 429, it says:
"an associative stacking semicategory in which
such that there is a special object which is neutral for the stacking operation.", I think this should be changed to:
"an associative stacking semicategory in which
there is a special object which is neutral for the stacking operation."

**Comment by antonioterpin** [comment]
Thank you for noticing, we addressed the issue in https://github.com/ACT4E/ACT4E/pull/673
