### ISSUE TITLE
Parallelism /  Parallel stacking / 2022-12-09: Typo categories --> semi categories

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#646]
Chapter: Parallelism
Section:  Parallel stacking
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 31. Parallelism / Types of stacking operations / Remark 31.1. on page 430, it says under the second bullet point:
"... For these categories we also want to consider
appropriate traces.", I think this should be changed to:
... For these semicategories we also want to consider
appropriate traces."

**Comment by antonioterpin** [comment]
Thanks! Addressed in https://github.com/ACT4E/ACT4E/pull/688
