### ISSUE TITLE
Naturality /  Natural transformations are morphisms between functors / 2022-12-09: Mistake in definition of identity natural transformation

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#647]
Chapter: Naturality
Section:  Natural transformations are morphisms between functors
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 35.3. Natural transformations are morphisms between functors / Definition 35.6 (Identity natural transformation), the identity natural transformation is defined as:
"(id𝐹)_𝑋 ∶= id_𝑋 ∀ 𝑋 ∈ Ob_C.", which I think is a mistake, because id_𝑋 is the identity morphism in C, but it should be the identity morphism in D, i.e. id_𝐹(𝑋). The corrected definition I think should be:
"(id𝐹)_𝑋 ∶= id_𝐹(𝑋) ∀ 𝑋 ∈ Ob_C."

**Comment by antonioterpin** [comment]
Thank you. You are right, we addressed the issue in PR https://github.com/ACT4E/ACT4E/pull/671
