### ISSUE TITLE
Adjunctions /   Product-Hom adjunction / 2022-12-09: Mistake in example of a "Product-Hom" adjunction

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#648]
Chapter: Adjunctions
Section:   Product-Hom adjunction
Version: 2022-12-09

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 36.5. Product-Hom adjunction the equation (50) says:
"𝐹(𝑓) = 𝑓 × id_𝐁", but I think it should be corrected to
"𝐹(𝑓) = id𝐁 × 𝑓".

**Comment by antonioterpin** [comment]
Thank you, you are right! We addressed the issue in https://github.com/ACT4E/ACT4E/pull/675

**Comment by JonathanLorand** [comment]
fixed. thank you!
