### ISSUE TITLE
Trade-offs /   More general preferences / 2022-12-09

### ISSUE THREAD

**Issue by HuangYujun-JunkyTalent** [ACT4E/ACT4E#651]
Chapter: Trade-offs
Section:   More general preferences
Version: 2022-12-09

Check all that apply:
- (x) Something incorrect
- (x) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

Something seems incorrect: in Def 9.23, equation (17) should be  $p \leq q,  r \leq s$ implies $p \leq s \lor r \leq q$

Something not clear: maybe it's clearer to introduce Semiorder based on utility functions, just like Wikipedia: [Wiki: Semiorder](https://en.wikipedia.org/wiki/Semiorder)

**Comment by kimhanm** [comment]
Thank you. The condition is that of **semi-transitivity**
$p \leq q \land q \leq r \implies p \leq s \lor s \leq r$
See Dean T. Jamison and Lawrence J. Lau - Semiorders and the theory of choice [1,2]

[1] [https://www.jstor.org/stable/1913813](https://www.jstor.org/stable/1913813) 
[2] [https://doi.org/10.2307/1913813](https://doi.org/10.2307/1913813)
