### ISSUE TITLE
Constructing categories /  Arrow construction / 2023-03-21: opposite category definition: different definitions of f^op

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#702]
Chapter: Constructing categories
Section:  Arrow construction
Version: 2023-03-21

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 17. Constructing categories / 17.3. Opposite Category / Definition 17.6 (Opposite category), the function is defined as 𝑓op ∶ 𝑌 →Cop 𝑋. But later in the same definition of opposite categories it is defined as 𝑓op ∶ 𝑋 →Cop 𝑌.
Furthermore, I think the part "Graphically, given..." is not representing the correct picture of the functions 𝑓 and 𝑓op as defined in the line above.

**Comment by JonathanLorand** [comment]
thanks @linusschoch, now fixed.
