### ISSUE TITLE
Constructing categories /  Disjoint Union of Categories / 2023-03-21: Definition of Product of Categories: Confusing object definition

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#704]
Chapter: Constructing categories
Section:  Disjoint Union of Categories
Version: 2023-03-21

Check all that apply:
- ( ) Something incorrect
- (X) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 17. Constructing categories / 17.1. Product of Categories / Definition 17.1 (Cartesian product of categories), the objects X, Y, Z and U are defined in a way, which is confusing:
- Under 1., 𝑋 ∈ ObC and 𝑌 ∈ ObD. This makes sense.
- Under 2.,  𝑋 ∈ ObC and 𝑌 ∈ ObC, Z ∈ ObD and U ∈ ObD. Since Y has been defined under 1. to be an object of D, I think this should again be the definition in 2. One would then have: ⟨𝑓, 𝑔⟩∶ ⟨𝑋, Y⟩ → ⟨Z, 𝑈⟩, which makes intuitively more sense than changing the definition of the objects.

**Comment by JonathanLorand** [comment]
agree, thanks for catching that @linusschoch. will be fixed.

**Comment by antonioterpin** [comment]
Thank you, fixed in https://github.com/ACT4E/ACT4E/pull/709
