### ISSUE TITLE
Specialization /  Subcategories of endomorphisms / 2023-03-21: Typo definition of Subcategory

### ISSUE THREAD

**Issue by linusschoch** [ACT4E/ACT4E#705]
Chapter: Specialization
Section:  Subcategories of endomorphisms
Version: 2023-03-21

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.
In section 21. Specialization / 21.1. Subcategories / Definition 21.1 (Subcategory), there is a typo:
- "2. For any two objects 𝑋,𝑌 ∈ ObD, the morphisms of D between of them..." should be corrected to
- "2. For any two objects 𝑋,𝑌 ∈ ObD, the morphisms of D between them..."

**Comment by JonathanLorand** [comment]
thanks @linusschoch

**Comment by antonioterpin** [comment]
Thank you! Fixed in https://github.com/ACT4E/ACT4E/pull/708
