### ISSUE TITLE
(Semi)categories /  Diagrams / 2023-07-30

### ISSUE THREAD

**Issue by NicolaMedici** [ACT4E/ACT4E#833]
Chapter: (Semi)categories
Section:  Diagrams
Version: 2023-07-30

page 264, definition 13.15: "all morphisms that arise from following paths in the diagram from 𝑋 to 𝑌 are in fact equal." Here "following" does not make much sense and could be deleted

**Comment by itiskawa** [comment]
ended up not changing, as i thought it was okay as is
