### ISSUE TITLE
Graphs /  Graph homomorphisms / 2023-09-20

### ISSUE THREAD

**Issue by Perian-Yan** [ACT4E/ACT4E#873]
Chapter: Graphs
Section:  Graph homomorphisms
Version: 2023-09-20

Check all that apply:
- (x) Something incorrect
- (x) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

two typos:
**Page 206, Example 12.7**: "...  exception made for 𝐹.(e) = x ... ".  What is the 'x' here? 

**Page 207, the last sentence**: " ... describe a graph homomorphism between 𝒢 and 𝒢' ". It should be "between 𝒢1 and 𝒢2."

**Comment by burkLeon** [comment]
Changed the "hard" coded $\funaob(e)=x$ to $\funaob(e)=\alpha$ to correspond to the picture. Maybe it would be nicer to use the same globally defined variable as in the picture
