### ISSUE TITLE
Translation /  Functors / 2023-09-20

### ISSUE THREAD

**Issue by Perian-Yan** [ACT4E/ACT4E#883]
Chapter: Translation
Section:  Functors
Version: 2023-09-20

Check all that apply:
- ( ) Something incorrect
- ( x ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

On the page 308, Example 19.3, Equation (2):
the first row is the composition of a set and the morphism 
$\\{f(c)|c \in C\\} ; F(g)$
which looks confused to me. Should It be:
$F(g)(\\{f(c)|c \in C\\})$
instead ?

**Comment by JonathanLorand** [comment]
resolved
