### ISSUE TITLE
Poset bounds /   Antichains / 2023-09-20

### ISSUE THREAD

**Issue by Perian-Yan** [ACT4E/ACT4E#886]
Chapter: Poset bounds
Section:   Antichains
Version: 2023-09-20

Check all that apply:
- (x) Something incorrect
- (x) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

On page 353, Lemma 24.15 claims that the upper closure is an antitone map. However, the proof goes with "given $S_1 \subseteq S_2$, we get $\uparrow S_1 \subseteq \uparrow S_2$". This actually preserves the order and should prove upper closure is a monotone map, right?

**Comment by AndreaCensi** [comment]
fixed in devel version
