### ISSUE TITLE
Feasibility /  The category of design problems \DP  / 2023-09-20

### ISSUE THREAD

**Issue by burkLeon** [ACT4E/ACT4E#888]
Chapter: Feasibility
Section:  The category of design problems \DP 
Version: 2023-09-20

Check all that apply:
- (X) Something incorrect
- ( ) Something not clear
- ( ) Something missing

Please describe more in detail below. Feel free to change the title to something more informative.

When proving that $$ G \colon DP \to DPI$ is indeed a functor, there seems to be a mistake when "massaging $I'$ to obtain $I$. Indeed, the set in the second row seems to have greater cardinality than the one in the third row, so it is not clear how equality should hold.

**Comment by AndreaCensi** [comment]
Good catch. It was a remain when we had a different definition of DPI where the implementation sets were defined up to isomorphisms.
